server:
  port: 8080
  tomcat.uri-encoding: UTF-8
  servlet.context-path: /kirck007
 

spring:
    profiles:
        include: datasourse
    redis:
      #数据库索引
      host: 192.168.4.214
      port: 6379
      password: 62515608
      jedis:
        pool:
          #最大连接数
          max-active: 8
          #最大阻塞等待时间(负数表示没限制)
          max-wait: -1
          #最大空闲
          max-idle: 8
          #最小空闲
          min-idle: 0
      #连接超时时间
      timeout: 10000   
      
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8 
      serialization: 
        FAIL_ON_EMPTY_BEANS: false
